### ISSUE TITLE
No matter What I do Installation keeps failing

### ISSUE THREAD

**Issue by peterhanania** [lorencerri/quick.db#198]
**Here is the code:**  
Urgent help needed.

C:\Users\Pc\Downloads\koko>npm i quick.db

> better-sqlite3@7.1.0 install C:\Users\Pc\Downloads\koko\node_modules\better-sqlite3
> prebuild-install || npm run build-release

prebuild-install WARN install No prebuilt binaries found (target=12.18.4 runtime=node arch=x64 libc= platform=win32)

> better-sqlite3@7.1.0 build-release C:\Users\Pc\Downloads\koko\node_modules\better-sqlite3
> node-gyp rebuild --release

C:\Users\Pc\Downloads\koko\node_modules\better-sqlite3>if not defined npm_config_node_gyp (node "C:\Users\Pc\Downloads\koko\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --release )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild --release )
Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
  extract_sqlite3
  sqlite3.c
  win_delay_load_hook.cc
  sqlite3.vcxproj -> C:\Users\Pc\Downloads\koko\node_modules\better-sqlite3\build\Release\\sqlite3.lib
  better_sqlite3.cpp
  win_delay_load_hook.cc
**C:\\Users\\Pc\\AppData\\Local\\node-gyp\\Cache\\12.18.4\\x64\\node.lib : fatal error LNK1127: library is corrupt [C:\Us
ers\Pc\Downloads\koko\node_modules\better-sqlite3\build\better_sqlite3.vcxproj]**
  test_extension.c
  win_delay_load_hook.cc
     Creating library C:\Users\Pc\Downloads\koko\node_modules\better-sqlite3\build\Release\test_extension.lib and objec
  t C:\Users\Pc\Downloads\koko\node_modules\better-sqlite3\build\Release\test_extension.exp
  test_extension.vcxproj -> C:\Users\Pc\Downloads\koko\node_modules\better-sqlite3\build\Release\\test_extension.node
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"
gyp ERR! cwd C:\Users\Pc\Downloads\koko\node_modules\better-sqlite3
gyp ERR! node -v v12.18.4
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! better-sqlite3@7.1.0 build-release: `node-gyp rebuild --release`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the better-sqlite3@7.1.0 build-release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Pc\AppData\Roaming\npm-cache\_logs\2020-12-21T18_33_49_529Z-debug.log
npm WARN canvas-constructor@4.1.0 requires a peer of canvas@* but none is installed. You must install peer dependencies yourself.
npm WARN discord.js-commando@0.10.0 requires a peer of discord.js@^11.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js-commando@0.10.0 requires a peer of sqlite@^2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! better-sqlite3@7.1.0 install: `prebuild-install || npm run build-release`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the better-sqlite3@7.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Pc\AppData\Roaming\npm-cache\_logs\2020-12-21T18_33_50_504Z-debug.log

Please lemme know if anyone finds something

**Comment by strikingwd** [comment]
im getting the exact same thing

**Comment by SebiTalent04** [comment]
same here

**Comment by peterhanania** [comment]
> im getting the exact same thing

I Fixed it bro just uninstall node.js and delete node modules, then reinstall node.js v12.16.1. Worked for me

**Comment by peterhanania** [comment]
> same here
I Fixed it bro just uninstall node.js and delete node modules, then reinstall node.js v12.16.1. Worked for me

**Comment by SebiTalent04** [comment]
im gonna try it, thanks

**Comment by peterhanania** [comment]
> im gonna try it, thanks

Np, lemme know if it works

**Comment by SebiTalent04** [comment]
nah, doesn't work even I downgrade node

D:\Projects\UsefulBot\node_modules\better-sqlite3>if not defined npm_config_node_gyp (node "C:\Users\Sebi\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --release )  else (node "C:\Users\Sebi\AppData\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild --release )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  extract_sqlite3
  sqlite3.c
  win_delay_load_hook.cc
  sqlite3.vcxproj -> D:\Projects\UsefulBot\node_modules\better-sqlite3\build\Release\\sqlite3.lib
  better_sqlite3.cpp
  win_delay_load_hook.cc
C:\\Users\\Sebi\\AppData\\Local\\node-gyp\\Cache\\12.16.1\\x64\\node.lib : fatal error LNK1106: invalid file or disk full: cannot seek to 0x2FC71E [D:\Projects\UsefulBot\node_modules\better-sqli
te3\build\better_sqlite3.vcxproj]
  test_extension.c
  win_delay_load_hook.cc
C:\\Users\\Sebi\\AppData\\Local\\node-gyp\\Cache\\12.16.1\\x64\\node.lib : fatal error LNK1106: invalid file or disk full: cannot seek to 0x2FC71E [D:\Projects\UsefulBot\node_modules\better-sqli
te3\build\test_extension.vcxproj]
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Sebi\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Sebi\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"
gyp ERR! cwd D:\Projects\UsefulBot\node_modules\better-sqlite3
gyp ERR! node -v v12.16.1
gyp ERR! node-gyp -v v7.1.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! better-sqlite3@7.1.2 build-release: `node-gyp rebuild --release`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the better-sqlite3@7.1.2 build-release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Sebi\AppData\Roaming\npm-cache\_logs\2021-01-03T12_40_23_819Z-debug.log
npm WARN useful-bot@2.1.0 No description
npm WARN useful-bot@2.1.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! better-sqlite3@7.1.2 install: `prebuild-install || npm run build-release`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the better-sqlite3@7.1.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Sebi\AppData\Roaming\npm-cache\_logs\2021-01-03T12_40_24_153Z-debug.log

**Comment by peterhanania** [comment]
> nah, doesn't work even I downgrade node
> 
> D:\Projects\UsefulBot\node_modules\better-sqlite3>if not defined npm_config_node_gyp (node "C:\Users\Sebi\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild --release ) else (node "C:\Users\Sebi\AppData\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild --release )
> Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
> extract_sqlite3
> sqlite3.c
> win_delay_load_hook.cc
> sqlite3.vcxproj -> D:\Projects\UsefulBot\node_modules\better-sqlite3\build\Release\sqlite3.lib
> better_sqlite3.cpp
> win_delay_load_hook.cc
> C:\Users\Sebi\AppData\Local\node-gyp\Cache\12.16.1\x64\node.lib : fatal error LNK1106: invalid file or disk full: cannot seek to 0x2FC71E [D:\Projects\UsefulBot\node_modules\better-sqli
> te3\build\better_sqlite3.vcxproj]
> test_extension.c
> win_delay_load_hook.cc
> C:\Users\Sebi\AppData\Local\node-gyp\Cache\12.16.1\x64\node.lib : fatal error LNK1106: invalid file or disk full: cannot seek to 0x2FC71E [D:\Projects\UsefulBot\node_modules\better-sqli
> te3\build\test_extension.vcxproj]
> gyp ERR! build error
> gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
> gyp ERR! stack at ChildProcess.onExit (C:\Users\Sebi\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:194:23)
> gyp ERR! stack at ChildProcess.emit (events.js:311:20)
> gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
> gyp ERR! System Windows_NT 10.0.19042
> gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Users\Sebi\AppData\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild" "--release"
> gyp ERR! cwd D:\Projects\UsefulBot\node_modules\better-sqlite3
> gyp ERR! node -v v12.16.1
> gyp ERR! node-gyp -v v7.1.2
> gyp ERR! not ok
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! better-sqlite3@7.1.2 build-release: `node-gyp rebuild --release`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the better-sqlite3@7.1.2 build-release script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> npm WARN Local package.json exists, but node_modules missing, did you mean to install?
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! C:\Users\Sebi\AppData\Roaming\npm-cache_logs\2021-01-03T12_40_23_819Z-debug.log
> npm WARN useful-bot@2.1.0 No description
> npm WARN useful-bot@2.1.0 No repository field.
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! better-sqlite3@7.1.2 install: `prebuild-install || npm run build-release`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the better-sqlite3@7.1.2 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! C:\Users\Sebi\AppData\Roaming\npm-cache_logs\2021-01-03T12_40_24_153Z-debug.log

Wait I think so 
Step 1 uninstall node and re install
Step 2 make sure to delete node modules 
Step 3 do npm I-g node-gyp@latest
Step 4 do npm i

**Comment by peterhanania** [comment]
npm i -g node-gyp@latest

**Comment by SebiTalent04** [comment]
I followed your steps and after the last it's givin me this

PS D:\Projects\UsefulBot> npm i

> better-sqlite3@7.1.2 install D:\Projects\UsefulBot\node_modules\better-sqlite3
> prebuild-install || npm run build-release

prebuild-install WARN install No prebuilt binaries found (target=15.5.0 runtime=node arch=x64 libc= platform=win32)

> better-sqlite3@7.1.2 build-release D:\Projects\UsefulBot\node_modules\better-sqlite3
> node-gyp rebuild --release


D:\Projects\UsefulBot\node_modules\better-sqlite3>if not defined npm_config_node_gyp (node "C:\Users\Sebi\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --release )  else (node "C:\Users\Sebi\AppData\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild --release )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  extract_sqlite3
  sqlite3.c
  win_delay_load_hook.cc
  sqlite3.vcxproj -> D:\Projects\UsefulBot\node_modules\better-sqlite3\build\Release\\sqlite3.lib
  better_sqlite3.cpp
d:\projects\usefulbot\node_modules\better-sqlite3\build\src\objects\database.lzz(364): warning C4309: 'static_cast': tr
uncation of constant value [D:\Projects\UsefulBot\node_modules\better-sqlite3\build\better_sqlite3.vcxproj]
  win_delay_load_hook.cc
C:\\Users\\Sebi\\AppData\\Local\\node-gyp\\Cache\\15.5.0\\x64\\node.lib : fatal error LNK1127: library is corrupt [D:\P
rojects\UsefulBot\node_modules\better-sqlite3\build\better_sqlite3.vcxproj]
  test_extension.c
  win_delay_load_hook.cc
     Creating library D:\Projects\UsefulBot\node_modules\better-sqlite3\build\Release\test_extension.lib and object D:\
  Projects\UsefulBot\node_modules\better-sqlite3\build\Release\test_extension.exp
  Generating code
  All 3 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
  Finished generating code
  test_extension.vcxproj -> D:\Projects\UsefulBot\node_modules\better-sqlite3\build\Release\\test_extension.node
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Sebi\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:376:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:284:12)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Sebi\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"
gyp ERR! cwd D:\Projects\UsefulBot\node_modules\better-sqlite3
gyp ERR! node -v v15.5.0
gyp ERR! node-gyp -v v7.1.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! better-sqlite3@7.1.2 build-release: `node-gyp rebuild --release`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the better-sqlite3@7.1.2 build-release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Sebi\AppData\Roaming\npm-cache\_logs\2021-01-03T12_54_05_241Z-debug.log
npm WARN useful-bot@2.1.0 No description
npm WARN useful-bot@2.1.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! better-sqlite3@7.1.2 install: `prebuild-install || npm run build-release`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the better-sqlite3@7.1.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Sebi\AppData\Roaming\npm-cache\_logs\2021-01-03T12_54_05_481Z-debug.log

**Comment by rhld16** [comment]
As you are on Windows, you may have to take additional steps to install better-sqlite3. [Read this](https://github.com/JoshuaWise/better-sqlite3/blob/master/docs/troubleshooting.md)
